eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.54:8761/eureka/
      
server:
  port: 8766
  
spring:
  application:
    name: eshop-dataaggr-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.31.223:3306/eshop
    username: root
    password: root
  rabbitmq:
    host: 192.168.31.223
    port: 5672  
    username: rabbitadmin  
    password: 123456